const fs=require("node:fs"),assert=require("node:assert/strict"),vm=require("node:vm");
const view=fs.readFileSync("Views/Report/_C12MedicalReceiptSummary.cshtml","utf8");
const css=fs.readFileSync("wwwroot/css/site.css","utf8");
const catalog=fs.readFileSync("Services/ReportCatalogService.cs","utf8");
assert.match(view,/type="date"/);assert.match(view,/partial name="_TableSkeleton"/);
assert.ok(view.indexOf("明細預覽／列印")<view.indexOf("彙總預覽／列印"));
assert.match(view,/item1,row\.item2,row\.item3/);assert.match(view,/summaryTotals\.received/);
assert.match(css,/@page\{size:A4 portrait/);assert.match(css,/\.c12-paper/);
assert.match(css,/\.c12-paper\{width:210mm;min-height:297mm/);
assert.match(css,/\.c12-visit\{break-inside:avoid/);
assert.equal((catalog.match(/Report\("C12"/g)||[]).length,1,"C12 must appear once in the menu");
assert.match(view,/病歷號 <i>\*<\/i>/);assert.doesNotMatch(view,/病歷號／身分證號/);
assert.match(view,/class="advanced-grid c12-query-grid"/);
assert.doesNotMatch(view,/舊科別碼/);
assert.doesNotMatch(view,/chop1sec/);
assert.doesNotMatch(view,/<datalist/);
assert.match(view,/class="report-autocomplete"/);
assert.match(view,/class="report-autocomplete-panel" role="listbox"/);
assert.match(view,/class="report-autocomplete-option"/);
assert.match(view,/role="combobox"/);
assert.match(view,/aria-label="第一頁"[^>]*:disabled="loading\|\|currentPage===1"[^>]*@@click="currentPage=1"[^>]*>‹‹<\/button>/);
assert.match(view,/aria-label="最後一頁"[^>]*:disabled="loading\|\|currentPage===totalPages"[^>]*@@click="currentPage=totalPages"[^>]*>››<\/button>/);
assert.match(view,/role="option"/);
assert.match(css,/\.report-autocomplete-panel\{[^}]*width:100%/);
assert.match(css,/\.report-autocomplete-panel\{[^}]*border-radius:10px/);
assert.match(view,/fetch\("\/Report\/GetC12SectionOptions"\)/);
assert.match(view,/v-for="row in pagedRows"/);
for(const heading of ["日期","時段","診間","序號","科別","醫師","科目","健保","自付","優待／記帳","實收"]) assert.ok(view.includes(`<th>${heading}</th>`),`missing table heading: ${heading}`);
assert.match(view,/共 \{\{detailRows\.length\}\} 筆/);
assert.match(view,/<option :value="10">10 筆<\/option><option :value="30">30 筆<\/option><option :value="50">50 筆<\/option>/);
assert.match(view,/detailRows\(\).*report\?\.detailRows/s);
assert.match(view,/pagedRows\(\).*slice\(start,start\+this\.pageSize\)/s);
assert.match(view,/totalPages\(\).*Math\.ceil\(this\.detailRows\.length\/this\.pageSize\)/s);
assert.match(view,/openPreview\(type\)\{if\(this\.report\)\{this\.printDate=this\.formatTaipeiDate\(new Date\(\)\);this\.preview=type\}\}/);
assert.match(view,/preview=null/);
const detailStart=view.indexOf(`<template v-if="preview==='detail'">`);
const summaryStart=view.indexOf(`<template v-else>`,detailStart);
const previewEnd=view.indexOf(`</article>`,summaryStart);
const detailPreview=view.slice(detailStart,summaryStart);
assert.match(detailPreview,/v-for="visit in report\.detailVisits"/);
assert.match(detailPreview,/item1,row\.item2,row\.item3/);
assert.match(detailPreview,/visit\.total/);
assert.match(detailPreview,/visit\.insuranceTotal/);
assert.match(detailPreview,/visit\.discountTotal/);
assert.match(detailPreview,/visit\.receivedTotal/);
assert.doesNotMatch(detailPreview,/discountOrOnAccountAmount/);
const summaryPreview=view.slice(summaryStart,previewEnd);
assert.match(summaryPreview,/row\.insuranceAmount/);
assert.match(summaryPreview,/row\.rawSelfPayAmount/);
assert.doesNotMatch(summaryPreview,/row\.discountOrOnAccountAmount/);
for(const total of ["total","insurance","discountOrOnAccount","received"]) assert.match(summaryPreview,new RegExp(`summaryTotals\\.${total}`));
assert.match(view,/:disabled="!report\?\.hasVisits"/);
assert.match(detailPreview,/亞東紀念醫院/);
assert.match(detailPreview,/醫療費用收據彙總證明/);
assert.match(detailPreview,/【費用明細】/);
assert.match(detailPreview,/class="c12-detail-meta c12-print-meta"/);
assert.match(detailPreview,/class="c12-meta-left"[\s\S]*列印日期[\s\S]*病歷號[\s\S]*資料起日/);
assert.match(detailPreview,/class="c12-meta-center"[\s\S]*姓名[\s\S]*資料迄日/);
assert.match(detailPreview,/class="c12-meta-right"[\s\S]*頁數[\s\S]*身分證字號[\s\S]*診別/);
assert.match(detailPreview,/列印日期：\{\{printDate\}\}/);
assert.match(detailPreview,/頁數：<span class="c12-page-number"/);
assert.match(detailPreview,/病歷號：\{\{report\.patient\.medicalRecordNumber\}\}/);
assert.match(detailPreview,/姓名：\{\{report\.patient\.name\}\}/);
assert.match(detailPreview,/身分證字號：\{\{report\.patient\.nationalId\}\}/);
assert.match(detailPreview,/資料起日：\{\{displayRoc\(report\.criteria\.startDate\)\}\}/);
assert.match(detailPreview,/資料迄日：\{\{displayRoc\(report\.criteria\.endDate\)\}\}/);
assert.match(detailPreview,/診別：\{\{report\.criteria\.roomTypeLabel\}\}/);
assert.equal((detailPreview.match(/<th>項目<\/th><th>健保<\/th><th>自付<\/th>/g)||[]).length,3);
assert.match(css,/\.c12-detail-paper/);
assert.match(css,/border:1px solid #000/);
assert.match(css,/counter\(page\).*counter\(pages\)/);
assert.match(summaryPreview,/class="c12-summary-paper"/);
assert.match(summaryPreview,/【費用彙總】/);
assert.match(summaryPreview,/class="c12-summary-table"/);
assert.match(summaryPreview,/<th>項目名稱<\/th><th>健保費用<\/th><th>自付費用<\/th>/);
assert.match(summaryPreview,/class="c12-summary-totals"[\s\S]*【合計】[\s\S]*總醫療費[\s\S]*健保申請[\s\S]*優待／記帳金額[\s\S]*實收金額/);
assert.match(summaryPreview,/class="c12-summary-footer"[\s\S]*※請妥善保存，以免個人資料外洩！[\s\S]*c12-page-number/);
assert.match(css,/\.c12-print-meta\{display:grid;grid-template-columns:/);
assert.match(css,/\.c12-summary-footer\{/);
global.window={};
vm.runInThisContext(view.match(/<script>([\s\S]*)<\/script>/)[1]);
const component=window.ReportComponents.C12Report;
const rows=Array.from({length:28},(_,index)=>({sequence:index+1}));
assert.deepEqual(component.computed.pagedRows.call({detailRows:rows,currentPage:1,pageSize:10}).map(row=>row.sequence),[1,2,3,4,5,6,7,8,9,10]);
assert.deepEqual(component.computed.pagedRows.call({detailRows:rows,currentPage:3,pageSize:10}).map(row=>row.sequence),[21,22,23,24,25,26,27,28]);
assert.equal(component.computed.totalPages.call({detailRows:rows,pageSize:10}),3);
assert.equal(component.computed.totalPages.call({detailRows:rows,pageSize:30}),1);
const previewContext={report:{hasVisits:true},preview:null,currentPage:3,pageSize:10,printDate:"",formatTaipeiDate:()=>"2026/09/14"};
component.methods.openPreview.call(previewContext,"detail");
assert.equal(previewContext.preview,"detail");
assert.equal(previewContext.printDate,"2026/09/14");
assert.equal(previewContext.currentPage,3);
assert.equal(previewContext.pageSize,10);
assert.equal(component.methods.formatTaipeiDate.call({},new Date("2026-09-13T16:30:00Z")),"2026/09/14");
(async()=>{
    const originalFetch=global.fetch;
    try{
        global.fetch=async()=>({ok:true,json:async()=>[{code:"11910",name:"心臟內科"}]});
        const optionContext={sectionOptions:[],sectionError:""};
        await component.methods.loadSectionOptions.call(optionContext);
        assert.deepEqual(optionContext.sectionOptions,[{code:"11910",name:"心臟內科"}]);
        assert.equal(optionContext.sectionError,"");

        const filterContext={form:{newSection:"11910"},sectionOptions:[{code:"11910",name:"一般內科"},{code:"11920",name:"急診外科"}]};
        const filtered=component.computed.filteredSectionOptions.call(filterContext);
        assert.deepEqual(filtered,[{code:"11910",name:"一般內科"}]);
        const keyboardContext={filteredSectionOptions:filtered,sectionOpen:true,sectionActiveIndex:-1,form:{newSection:""},selectSectionOption:component.methods.selectSectionOption};
        component.methods.onSectionKeydown.call(keyboardContext,{key:"ArrowDown",preventDefault(){}});
        assert.equal(keyboardContext.sectionActiveIndex,0);
        component.methods.onSectionKeydown.call(keyboardContext,{key:"Enter",preventDefault(){}});
        assert.equal(keyboardContext.form.newSection,"11910");
        assert.equal(keyboardContext.sectionOpen,false);
        keyboardContext.sectionOpen=true;
        component.methods.onSectionKeydown.call(keyboardContext,{key:"Escape",preventDefault(){}});
        assert.equal(keyboardContext.sectionOpen,false);
        const outsideContext={$refs:{sectionAutocomplete:{contains:()=>false}},sectionOpen:true,sectionActiveIndex:0};
        component.methods.closeSectionOptionsFromOutside.call(outsideContext,{target:{}});
        assert.equal(outsideContext.sectionOpen,false);

        global.fetch=async()=>({ok:false,json:async()=>({title:"database details"})});
        await component.methods.loadSectionOptions.call(optionContext);
        assert.deepEqual(optionContext.sectionOptions,[]);
        assert.equal(optionContext.sectionError,"無法載入科別清單，仍可直接輸入科別代碼。");

        let submitted;
        global.fetch=async(url,request)=>{submitted={url,body:JSON.parse(request.body)};return{ok:true,json:async()=>({hasVisits:false,detailRows:[]})}};
        const searchContext={form:{startDate:"2026-09-01",endDate:"2026-09-14",source:"OpdEr",roomScope:"All",newSection:"11910",identity:"AB12"},loading:false,error:"",report:null,preview:null,searched:false,currentPage:3,sectionOpen:true};
        await component.methods.search.call(searchContext);
        assert.equal(submitted.url,"/Report/GetReportData");
        assert.equal(submitted.body.newSectionCode,"11910");
        assert.equal(Object.hasOwn(submitted.body,"chop1sec"),false);
        assert.equal(searchContext.currentPage,1);
    }finally{global.fetch=originalFetch}
    console.log("C12 report UI contract tests passed.");
})().catch(error=>{console.error(error);process.exitCode=1});
