using OpdAccrRptWeb.Models;
using OpdAccrRptWeb.Repositories;
using OpdAccrRptWeb.Services;
namespace OpdAccrRptWeb.Tests;
public sealed class C7ReportServiceTests
{
    [Fact] public async Task Query_UsesFreshDailyCallsAndMapsRows(){var repo=new Repo();var service=new C7ReportService(repo,new Units(),new NoCache());var result=await service.QueryAsync(new("2026-01-01","2026-01-02","0800","1200","u1",PageSize:10));Assert.Equal(new[]{"1150101","1150102"},repo.Days);Assert.Equal(2,result.AllRows.Count);Assert.All(result.AllRows,x=>{Assert.Equal("11930",x.SectionCode);Assert.Equal("急診",x.EncounterLabel);Assert.Equal("DC",x.Status);Assert.Equal(22,x.Amount);});}
    [Fact] public async Task Query_RejectsStaleIneligibleUser(){var repo=new Repo{Eligible=false};var service=new C7ReportService(repo,new Units(),new NoCache());await Assert.ThrowsAsync<ArgumentException>(()=>service.QueryAsync(new("2026-01-01","2026-01-01",InputUserId:"u1")));}
    [Fact] public async Task Query_BlankUser_IsRejectedBeforeEligibilityAndDetailQuery(){var repo=new Repo{Eligible=false};var service=new C7ReportService(repo,new Units(),new NoCache());await Assert.ThrowsAsync<ArgumentException>(()=>service.QueryAsync(new("2026-01-01","2026-01-01",InputUserId:"")));Assert.Equal(0,repo.EligibilityCalls);Assert.Empty(repo.Days);}
    private sealed class Repo:IC7ReportRepository{public bool Eligible=true;public int EligibilityCalls;public List<string> Days=[];public Task<IReadOnlyList<C7InputUser>> GetEligibleUsersAsync(string d,CancellationToken t=default){EligibilityCalls++;return Task.FromResult<IReadOnlyList<C7InputUser>>(Eligible?[new("U1","User")]:[]);}public Task<IC7ReportQuerySession> OpenSessionAsync(CancellationToken t=default)=>Task.FromResult<IC7ReportQuerySession>(new Session(this));private sealed class Session(Repo r):IC7ReportQuerySession{public Task<IReadOnlyList<C7SourceRow>> QueryDayAsync(C7ValidatedRequest q,string d,CancellationToken t=default){r.Days.Add(d);return Task.FromResult<IReadOnlyList<C7SourceRow>>([new("01","0221","X","Name","4","DC",2,"U1",10,20,11,22,"User",d,"A","M1","E")]);}public ValueTask DisposeAsync()=>ValueTask.CompletedTask;}}
    private sealed class Units:IOrganizationUnitCodeService{public Task<OrganizationUnitMapping?> ResolveLegacyCodeAsync(string n,bool a,CancellationToken t=default)=>Task.FromResult<OrganizationUnitMapping?>(null);public Task<OrganizationUnitMapping?> ResolveNewCodeAsync(string l,string r,OrganizationUnitMappingScope s,CancellationToken t=default)=>Task.FromResult<OrganizationUnitMapping?>(null);public Task<IReadOnlyList<OrganizationUnitMapping>> SearchAsync(string q,bool s,bool p,bool a,int l=20,CancellationToken t=default)=>Task.FromResult<IReadOnlyList<OrganizationUnitMapping>>([]);}
    private sealed class NoCache:IC7ReportResultCache{public bool TryGet(IReadOnlyDictionary<string,string?> f,out C7CachedResult r){r=null!;return false;}public void Set(IReadOnlyDictionary<string,string?> f,C7CachedResult r){}}
}
