const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const root=path.resolve(__dirname,".."),view=fs.readFileSync(path.join(root,"Views/Report/_M1DoctorDailyReport.cshtml"),"utf8"),preview=fs.readFileSync(path.join(root,"Views/DoctorDailyReport/Preview.cshtml"),"utf8"),script=fs.readFileSync(path.join(root,"wwwroot/js/reports/m1-doctor-daily-report.js"),"utf8"),app=fs.readFileSync(path.join(root,"wwwroot/js/report-app.js"),"utf8");
for(const value of ["page-title","panel query-panel","type=\"date\"","_TableSkeleton","empty-result","pagination","預覽／列印","Excel"])assert.match(view,new RegExp(value));
assert.doesNotMatch(view,/exportReport\('pdf'\)|>PDF</);
for(const value of ["處理日期","製表人","頁次：1","科別","醫師代號及姓名","民眾人數","健保人數","預約人數","預約比例","合計","上午人數","下午人數","夜間人數"])assert.match(preview,new RegExp(value));
for(const value of ["Model.HospitalName","Model.ProgramId","Model.QueryDate","Model.Groups","group.Label"])assert.match(preview,new RegExp(value.replace(".","\\.")));
assert.match(script,/M1_FUTURE_DATE_CONFIRMATION_REQUIRED/);assert.match(script,/window\.confirm/);assert.match(script,/this\.runId = null/);assert.match(script,/pageNumber: this\.currentPage/);assert.match(script,/\/medical-statistics\/doctor-daily\/query/);assert.match(script,/\/medical-statistics\/doctor-daily\/preview/);assert.match(script,/encodeURIComponent\(this\.runId\)/);assert.match(app,/M1:\s*window\.ReportComponents\.M1DoctorDailyReport/);assert.match(app,/\/medical-statistics\/doctor-daily/);
const window={ReportComponents:{}};vm.runInNewContext(script,{window,document:{}});const component=window.ReportComponents.M1DoctorDailyReport;const data=component.data.call({defaultStartDate:"2026-09-24"});assert.equal(data.form.reportDate,"2026-09-23");
console.log("m1 doctor daily UI tests passed");
