<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Entities\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.300" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="FemhDb">
      <HintPath>Infrastructure\FemhDb.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
