namespace OpdAccrRptWeb.Repositories;

internal static class C12Sql
{
    internal const string ResolveMedicalRecord = "SELECT M.chMrNo FROM OpdMrBasicTbl M WHERE M.chID = :InputIdentity";
    internal const string Patient = "SELECT M.chMrNo, M.chName, M.chID FROM OpdMrBasicTbl M WHERE M.chMrNo = :MrNo";
    internal const string SectionName = "SELECT S.chSecNo, S.chSecName FROM GenSectionTbl S WHERE S.chSecNo IN ({0})";
    internal const string SectionMapping = @"SELECT A.chSecNo FROM (SELECT RTRIM(S.chSecNo) chSecNo, RTRIM(S.chNewSecNo) chNewSecNo FROM GenSectionTbl S UNION SELECT RTRIM(P.chPlaNo), RTRIM(P.chNewPlaNo) FROM GenPlaceTbl P WHERE P.chPlaWork='1') A WHERE A.chSecNo IS NOT NULL AND A.chNewSecNo = :NewSectionCode";
    internal const string InpatientVisits = @"SELECT B.chOp1Date, B.chOp1Time, B.chOp1Room, B.intOp1No, B.chOp1Sec, B.chOp1DrName, B.chOp1MrNo, B.chOp1ClmFlg FROM IpdBasicTbl B WHERE B.chOp1Date BETWEEN :StartDate AND :EndDate AND (:ApplySection=0 OR B.chOp1Sec LIKE :SectionPrefix) AND B.chOp1MrNo=:MrNo AND B.chOp1ClmFlg <> 'D' ORDER BY B.chOp1Date,B.chOp1Time,B.chOp1Room,B.intOp1No";
    internal const string OutpatientVisits = @"SELECT B.chOp1Date, B.chOp1Time, B.chOp1Room, B.intOp1No, B.chOp1Sec, B.chOp1DrName, B.chOp1MrNo, NULL chOp1ClmFlg FROM OpdBasicTbl B WHERE B.chOp1Date BETWEEN :StartDate AND :EndDate AND (:ApplySection=0 OR B.chOp1Sec LIKE :SectionPrefix) AND B.chOp1MrNo=:MrNo AND (:RoomType NOT IN (1,2) OR (:RoomType=1 AND B.chOp1RoomType='E') OR (:RoomType=2 AND B.chOp1RoomType<>'E')) AND NOT EXISTS (SELECT 1 FROM OpdRegPtnTbl R WHERE R.chOp0Date=B.chOp1Date AND R.chOp0Time=B.chOp1Time AND R.chOp0Room=B.chOp1Room AND R.intOp0No=B.intOp1No AND R.chOp0DC='1') ORDER BY B.chOp1Date,B.chOp1Time,B.chOp1Room,B.intOp1No";
    internal const string InpatientCharges = @"SELECT O.chOp4DctName Name,SUM(O.rlOp4AMT1) AMT1,SUM(O.rlOp4AMT2) AMT2,SUM(O.rlOp4Sub3+O.rlOp4Sub5) AMT5 FROM IpdOrdTbl O WHERE O.chOp1Date=:VisitDate AND O.chOp1Time=:VisitTime AND O.chOp1Room=:VisitRoom AND O.intOp1No=:VisitNo AND O.chOp4Stat<>'DC' AND O.chOp4Dct<'51' AND (O.chOp4Proj NOT IN ('I','D') OR RTRIM(O.chOp4Proj) IS NULL) AND O.chOp4OrdNo NOT IN ('00-025','00-026') AND RTRIM(O.chOp4IDate) IS NOT NULL GROUP BY O.chOp4DctName HAVING SUM(O.rlOp4AMT1)<>0 OR SUM(O.rlOp4AMT2)<>0 OR SUM(O.rlOp4Sub3+O.rlOp4Sub5)<>0 UNION SELECT D.chOp3DctName,SUM(D.rlOp3AMT1),SUM(D.rlOp3AMT2),SUM(D.rlOp3Sub3+D.rlOp3Sub5) FROM IpdDrgTbl D WHERE D.chOp1Date=:VisitDate AND D.chOp1Time=:VisitTime AND D.chOp1Room=:VisitRoom AND D.intOp1No=:VisitNo AND D.chOp3Stat<>'DC' AND (D.chOp3Proj NOT IN ('I','D') OR RTRIM(D.chOp3Proj) IS NULL) AND (D.chOp3Rep3Flg<>'S' OR RTRIM(D.chOp3Rep3Flg) IS NULL) AND (D.chOp3Stat NOT IN ('09','10','11','12') OR RTRIM(D.chOp3Stat) IS NULL) AND RTRIM(D.chOp3IDate) IS NOT NULL GROUP BY D.chOp3DctName HAVING SUM(D.rlOp3AMT1)<>0 OR SUM(D.rlOp3AMT2)<>0 OR SUM(D.rlOp3Sub3+D.rlOp3Sub5)<>0";
    internal const string OutpatientCharges = @"SELECT O.chOp4DctName Name,SUM(O.rlOp4AMT1) AMT1,SUM(O.rlOp4AMT2) AMT2,SUM(O.rlOp4Sub3+O.rlOp4Sub5) AMT5 FROM OpdOrdTbl O WHERE O.chOp1Date=:VisitDate AND O.chOp1Time=:VisitTime AND O.chOp1Room=:VisitRoom AND O.intOp1No=:VisitNo AND O.chOp4Stat<>'DC' AND (:IsEmergencyTransfer=0 OR O.chOp4Proj NOT IN ('I','S') OR RTRIM(O.chOp4Proj) IS NULL) AND SUBSTR(O.chOp4Dct,1,2) NOT IN ('59','60','69','80') AND O.chOp4OrdNo NOT IN ('00-025','00-026') GROUP BY O.chOp4DctName HAVING SUM(O.rlOp4AMT1)<>0 OR SUM(O.rlOp4AMT2)<>0 OR SUM(O.rlOp4Sub3+O.rlOp4Sub5)<>0 UNION SELECT D.chOp3DctName,SUM(D.rlOp3AMT1),SUM(D.rlOp3AMT2),SUM(D.rlOp3Sub3+D.rlOp3Sub5) FROM OpdDrgTbl D WHERE D.chOp1Date=:VisitDate AND D.chOp1Time=:VisitTime AND D.chOp1Room=:VisitRoom AND D.intOp1No=:VisitNo AND D.chOp3Stat<>'DC' AND (:IsEmergencyTransfer=0 OR D.chOp3Proj NOT IN ('I','S') OR RTRIM(D.chOp3Proj) IS NULL) GROUP BY D.chOp3DctName HAVING SUM(D.rlOp3AMT1)<>0 OR SUM(D.rlOp3AMT2)<>0 OR SUM(D.rlOp3Sub3+D.rlOp3Sub5)<>0";
}
